# Introducing NumPy arrays

In [2]:
import numpy as np
import os

In [3]:
# create file path
# os package enables you to write polymorhpic file paths across operating systems
filepath = os.path.join("..", "..", "cds-vis-data", "data", "sample-data", "sample-data-01.csv")

In [4]:
filepath

'../../cds-vis-data/data/sample-data/sample-data-01.csv'

In [5]:
data = np.loadtxt(fname=filepath, delimiter=",")

In [6]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [7]:
data.dtype

dtype('float64')

In [8]:
data.shape

(60, 40)

In [11]:
data[0, 0]

0.0

In [14]:
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [16]:
# select whole row shorthand
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [17]:
# select whole column shorthand
data[:, 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# average score
np.mean(data)

6.14875

In [19]:
np.max(data)

20.0

In [20]:
np.min(data)

0.0

In [21]:
np.max(data, axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 19., 18., 17., 16., 15.,
       14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,
        1.])

Data types - Sequence types, map types, int/floats
PiP - Installing packages for python.
Introduction to Imports / modules - OS native module and numpy.
